title:              Hyunsong's Blog
email:              HyunSongKwon@gmail.com
description:        A Blog Theme by Start Bootstrap
author:             HyunSongKwon
baseurl:            "HyunSongKwon.github.io"
url:                "https://HyunSongKwon.github.io"

# Social Profiles
github_username:    HyunSongKwon
linkedin_username:  HyunSongKwon

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
